site_name: PyODX
site_url: https://pyodx.webodm.org
site_description: A Python SDK for NodeODX API
repo_url: https://github.com/WebODM/PyODX
repo_name: WebODM/PyODX

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.copy
    - navigation.instant
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.suggest

nav:
  - Home: index.md
  - Installation: installation.md
  - Examples: examples.md
  - API Reference: reference.md
  - Migrate From PyODM: migration.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
            show_root_heading: true
            members_order: source
            docstring_style: google

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - toc:
      permalink: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/WebODM/PyODX
